language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

script:
  - cargo build -v --release
  - cargo test -v --release
  - cargo doc
