language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:
  - (cargo install rustfmt || true)

script:
  - cargo fmt -- --write-mode diff
  - cargo build -v
  - cargo test -v
  - cargo doc
