language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:
  - rustup run beta cargo install -f rustfmt

script:
  - rustup run beta cargo fmt -- --write-mode diff
  - cargo build -v
  - cargo test -v
  - cargo doc
