language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "beta" ]; then
      cargo install rustfmt;
    fi

script:
  - if [ "$TRAVIS_RUST_VERSION" == "beta" ]; then
      cargo fmt -- --write-mode diff;
    fi
  - cargo build -v --release
  - cargo test -v --release
  - cargo doc
