language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:  
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - travis-cargo --only beta install rustfmt

script:
  - travis-cargo --only beta fmt -- --write-mode diff
  - cargo build -v
  - cargo test -v
  - cargo doc
