[package]
name = "nmea"
version = "0.0.5-pre"
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
description = "Simple NMEA 0183 parser"
documentation = "https://docs.rs/nmea/"
homepage = "https://github.com/flxo/rust-nmea"
license = "Apache-2.0"
keywords = ["NMEA", "gps", "glonass", "coordinate", "position"]

[dependencies]
error-chain = "0.10.0"
lazy_static = "0.2.2"
regex = "0.2.1"
time = "0.1.36"

[dev-dependencies]
quickcheck = "0.3"

[badges]
travis-ci = { repository = "Dushistov/rust-nmea" }
